import './globals.css'

import type { Metadata } from 'next'

import Header from './components/reusable/Header';
import Footer from './components/reusable/Footer';

//firebase
import { getFirebaseApp } from './firebase'
const app = getFirebaseApp();

//font
import { Outfit } from 'next/font/google'
const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'soma',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="flex flex-col min-h-screen">
          <div className='flex'>
            <Header />
          </div>
          <div className="flex-grow">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
