import './globals.css'

import type { Metadata } from 'next'
import dynamic from "next/dynamic";

import Header from "./compos/Macro/Header";

import { Outfit } from 'next/font/google'
import Footer from './compos/Macro/Footer';
const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'soma',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="flex flex-col min-h-screen">
          <div className='flex'>
            <Header />
          </div>
          <div className="flex-grow">
          {/* <div className=""> */}
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
