import './globals.css'

import type { Metadata } from 'next'
import dynamic from "next/dynamic";

import { Inter } from 'next/font/google'
import { Roboto } from "next/font/google";

import Header from "./compos/Macro/Header";

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'soma',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-col min-h-screen">
          <div className='flex'>
            <Header />
          </div>
          <div className="flex-grow">
          {/* <div className=""> */}
            {children}
          </div>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  )
}
